### PR TITLE
WebApi Formation Practice

### PR DESCRIPTION
**Pull request by abhish-knp**
secondaryBranch merge,

### CODE REVIEW

**Comment by abhish-knp** [comment]
File added on secondaryBranch

**Comment by abhish-knp** [comment]
@vinscom solution file on secondaryBranch.

**Comment by abhish-knp** [comment]
reviewed

**Comment by vinscom** [comment]
- Remove conflict
- Project should be in .Net 5

**Comment by abhish-knp** [comment]
Ok, removing conflict

**Review by abhish-knp — COMMENTED** [review]
reviewed

**Review by abhish-knp — COMMENTED** [review]
working on .net 5

**Comment by abhish-knp** [comment]
@vinscom pls check .net 5 framework added

**Comment by abhish-knp** [comment]
@vinscom  Conflict resolved

**Comment by vinscom** [comment]
- Program.cs should follow .Net 5 pattern, not .net 6.
- Give proper name to PR
- Why two folders v5WebApi and WA1012
- If I open mysolution.sln, is it pointing to v5WebApi and WA1012
- Give proper name to .sln Project like *PracticeProject*
- sln project should have 2 projects PracticeProject and PracticeProjectTest (Check how audit project is organised)
- Update Readme.md. Write what this project does.
- Remove .vs folder

**Comment by abhish-knp** [comment]
@vinscom pls review

**Comment by vinscom** [comment]
@abhish-knp Can you please go through *file changes* in PR ?
Are you sure you want all files ?

**Review by abhish-knp — COMMENTED** [review]
Selected working files

**Review by abhish-knp — COMMENTED** [review]
Problems : 
- I'm missing the process to work with git and vs code. 
- want to resolve code on vs code or VS studio.

**Pull request closed without merging**
